# Generated by Django 5.2.17 on 2026-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_required', models.CharField(blank=True, choices=[('Website Development', 'Website Development'), ('Mobile App Development', 'Mobile App Development'), ('Business Software Solutions', 'Business Software Solutions'), ('Cloud, Hosting & Domain', 'Cloud, Hosting & Domain'), ('Digital Marketing & SEO', 'Digital Marketing & SEO'), ('UI/UX & Branding', 'UI/UX & Branding'), ('AMC & Technical Support', 'AMC & Technical Support'), ('Other / Not sure yet', 'Other / Not sure yet')], max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
